### ISSUE TITLE
Document settings for adding a custom truststore

### ISSUE THREAD

**Issue by Haarolean** [kafbat/ui-docs#33]
```
server:
  ssl:
    trust-store: classpath:keycloak-truststore.jks
    trust-store-password: changeit
```
